-- Create Profiles Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  avatar_url text,
  birth_date date,
  birth_time time,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Create Plans Table (to track user subscription/limits)
create table public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  plan_type text default 'free', -- 'free' or 'pro'
  chat_count int default 0,
  last_chat_reset date default CURRENT_DATE,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for plans
alter table public.plans enable row level security;

create policy "Users can view own plan."
  on public.plans for select
  using ( auth.uid() = user_id );

-- Create Chats Table (for history)
create table public.chats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  message text not null,
  is_ai boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for chats
alter table public.chats enable row level security;

create policy "Users can view own chats."
  on public.chats for select
  using ( auth.uid() = user_id );

create policy "Users can insert own chats."
  on public.chats for insert
  with check ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'avatar_url');
  
  insert into public.plans (user_id)
  values (new.id);
  
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call handle_new_user
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
